config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "/timetable", to: "user_courses#index"
  get "/chatroom", to: "messages#index"
  root "static_pages#home"

  resources :users do
    member do
      resources :followings, :followers, only: :index
    end
  end

  resources :posts do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end

  resources :conversations, only: [:create] do
    resources :messages, only: [:create]

    member do
      post :close
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :groups, only: %i(index show)
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  default_scope -> { order(created_at: :desc) }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :logged_in_user
  before_action :find_post, only: %i(new create edit update destroy)
  before_action :find_comment, only: %i(edit update destroy)

  def create
    @comment = @post.comments.build comment_params
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post }
      else
        format.html { render @post }
      end
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    respond_to do |format|
      if @comment.update_attributes comment_params
        format.html { redirect_to @post }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.js
    end
    redirect_to @post
  end

  private

  def comment_params
    params.require(:comment).permit :content
  end

  def find_post
    @post = Post.find_by id: params[:post_id]

    return if @post
    flash[:danger] = "Can not find this post."
    redirect_to root_path
  end

  def find_comment
    @comment = @post.comments.find_by id: params[:id]

    return if @comment
    flash[:danger] = "Can not find this comment."
    redirect_to @post
  end
end

app/views/comments/_comment.html.erb
<% if comment.user_id.present? %>
  <div id="comment-<%= comment.id %>" class="current-comment">
    <div id="comment">
      <div class="user-name">
        <div class="gravatar-user">
          <% if comment.user.avatar? %>
            <%= image_tag comment.user.avatar.thumb.url, class: "img-avatar" %>
          <% else %>
            <%= gravatar_for post.user, size: 40 %>
          <% end %>
        </div>
        <%= link_to comment.user.name, user_path(comment.user) %>
        <div class="timestamp"><%= time_ago_in_words(comment.created_at).capitalize %> ago.</div>
      </div>

      <div class="content" >
        <%= comment.content %>
      </div>

      <% if comment.user == current_user %>
        <%= link_to "Edit", edit_post_comment_path(post, comment), remote: true %>
        <%= link_to "Delete", post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" }, remote: true %>
      <% end %>
      <div id="comment-id-<%= comment.id %>"></div>
    </div>
  </div>
<% end %>

app/views/comments/_comment_form.html.erb
<%= form_for([post, comment], remote: true) do |f| %>
  <%= f.text_field :content, placeholder: "Add a comment...", class: "form-control comment-content", id: "comment-content-#{post.id}"  %>
<% end %>

app/views/comments/destroy.js.erb
$('#comment-<%= comment.id %>').remove()

app/views/comments/edit.js.erb
$('#comment-id-<%= @comment.id %>').html("<%= j render 'comment_form', post: @post, comment: @comment %>")