config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "/timetable", to: "user_courses#index"
  get "/chatroom", to: "messages#index"
  root "static_pages#home"

  resources :users do
    member do
      resources :followings, :followers, only: :index
    end
  end

  resources :posts do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end

  resources :conversations, only: [:create] do
    resources :messages, only: [:create]

    member do
      post :close
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :groups, only: %i(index show)
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups, dependent: :destroy
  has_many :users, through: :user_groups
  has_many :posts, dependent: :destroy
  belongs_to :course

  scope :desc, -> { order created_at: :desc }
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :logged_in_user
  before_action :find_group, only: :show

  def index
    @groups = current_user.groups.includes(:course, :users)
  end

  def show
    @posts = @group.posts.includes(:user).desc.page(params[:page]).per(5)
    @post = current_user.posts.build
  end

  private

  def find_group
    @group = current_user.groups.find_by(id: params[:id])
  end
end

app/views/groups/index.html.erb
<div class="row">
  <h3>Your groups</h3>
  <hr>
  <div class="row">
    <% @groups.each do |group| %>
      <div class="col-md-4">
        <div class="well">
          <div class="row">
            <div class="col-md-9">
              <p><b><%= link_to(truncate(group.course.name, length: 60), group_path(group.id)) %></b></p>
            </div>
            <div class="col-md-3">
              <h3><%= group.users.size %> <i class="fa fa-user-circle-o"></i></h3>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<div class="container">
  <h2 class="text-center"><%= @group.course.name %></h2>
  <div class="row">
    <div class="col-md-3">
      <h3>List members</h3>
      <div class="well">
        <% @group.users.each do |user| %>
          <p><%= link_to user.name, user_path(user) %></p>
        <% end %>
      </div>
    </div>

    <div class="col-md-6">
      <%= form_for @post, remote: true do |f| %>
        <div class="form-group">
          <%= render "shared/error_messages" %>
          <%= f.text_field :content, placeholder: "Wanna announce something ?", class: "form-control" %>
          <%= f.hidden_field :group_id, value: @group.id %>
        </div>
        <span class="picture">
          <%= f.file_field :picture, accept: "image/jpeg,image/gif,image/png", class: "picture-field" %>
        <%= f.submit "Post", class: "btn btn-primary pull-right" %>
        </span>
      <% end %>

      <br><br>
      <% if @group.posts.any? %>
        <ol class="posts">
          <%= render @posts %>
        </ol>
        <%= paginate @posts, theme: "twitter-bootstrap-3" %>
      <% else %>
        <h3>You haven't created any post.</h3>
      <% end %>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>