config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "/timetable", to: "user_courses#index"
  get "/chatroom", to: "messages#index"
  root "static_pages#home"

  resources :users do
    member do
      resources :followings, :followers, only: :index
    end
  end

  resources :posts do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end

  resources :conversations, only: [:create] do
    resources :messages, only: [:create]

    member do
      post :close
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :groups, only: %i(index show)
end

app/views/shared/_error_messages.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@post.errors.count, "error") %>.
    </div>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="posts">
    <%= render @feed_items %>
  </ol>
  <%= paginate @feed_items, theme: "twitter-bootstrap-3" %>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_for @post, remote: true do |f| %>
  <%= render "shared/error_messages" %>

  <div class="field">
    <%= f.text_area :content, placeholder: "What's on your mind?", class: "form-control text-area", rows: 3 %>
  </div>

  <span class="picture">
    <%= f.file_field :picture, accept: "image/jpeg,image/gif,image/png", class: "picture-field" %>
  </span>

  <%= f.submit "Post", class: "form-control btn btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <%= link_to followers_path @user do %>
    <strong id="followers"><%= @user.followers.count %></strong> followers
  <% end %>

  <%= link_to followings_path @user do %>
    <strong id="following"><%= @user.following.count %></strong> following
  <% end %>
</div>