config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "/timetable", to: "user_courses#index"
  get "/chatroom", to: "messages#index"
  root "static_pages#home"

  resources :users do
    member do
      resources :followings, :followers, only: :index
    end
  end

  resources :posts do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end

  resources :conversations, only: [:create] do
    resources :messages, only: [:create]

    member do
      post :close
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :groups, only: %i(index show)
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :group, optional: true
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 500 }

  scope :desc, -> { order created_at: :desc }
  scope :feed, lambda { |following_ids, id|
    Post.where("user_id IN (?)
      OR user_id = (?)", following_ids, id)
  }

  mount_uploader :picture, PictureUploader
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user
  before_action :find_post, only: %i(show edit update destroy)

  def create
    @post = current_user.posts.build post_params

    respond_to do |format|
      if @post.save
        format.html { redirect_to group_path(@post.group) } if @post.group
        format.html { redirect_to root_path }
      else
        @feed_items = []
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  def show
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    respond_to do |format|
      if @post.update_attributes post_params
        format.html { redirect_to @post }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.js
    end
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit :content, :picture, :group_id
  end

  def find_post
    @post = Post.find_by id: params[:id]

    return if @post
    flash[:danger] = "Can not find this post."
    redirect_to root_path
  end
end

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
  <span class="user">
    <div class="gravatar-user">
      <% if post.user.avatar? %>
        <%= image_tag post.user.avatar.thumb.url, class: "img-avatar" %>
      <% else %>
        <%= gravatar_for post.user, size: 40 %>
      <% end %>
    </div>

    <%= link_to post.user.name, user_path(post.user) %>

    <% if current_page? root_path %> 
      <%= link_to " > #{post.group.course.name}", group_path(post.group) if post.group %>
    <% end %>

    <span class="timestamp">
      <%= link_to "Posted " + time_ago_in_words(post.created_at) + " ago.", post %>
    </span>
  </span>

  <span class="content">
    <%= post.content %>
    <%= image_tag post.picture.url if post.picture? %>
  </span>

  <div class="like-btn">
    <% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>

    <% if pre_like %>
      <%= link_to image_tag("liked.svg"), post_like_path(post, pre_like), class: "like", method: :delete, remote: true %>
    <% else %>
      <%= link_to image_tag("like.svg"), post_likes_path(post), class: "like", method: :post, remote: true %>
    <% end %>

    <span class="counter" id="post-counter-<%= post.id %>">
      <%= pluralize(post.likes.count, "like") %>
    </span>
  </div>
</li>

app/views/posts/create.js.erb
alert('Your post content is too long. It should not exceed 500 characters.');

app/views/posts/destroy.js.erb
$('#post-<%= post.id %>').remove();

app/views/posts/edit.js.erb
$('#post-id-<%= @post.id %>').html("<%= j render 'shared/post_form', post: @post %>");

app/views/posts/show.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="user">
    <div class="gravatar-user">
      <% if @post.user.avatar? %>
        <%= image_tag @post.user.avatar.thumb.url, class: "img-avatar" %>
      <% else %>
        <%= gravatar_for @post.user, size: 40 %>
      <% end %>
    </div>
    <%= link_to @post.user.name, user_path(@post.user) %>

    <span class="timestamp">
      Posted <%= time_ago_in_words(@post.created_at) %> ago.
    </span>
  </div>

  <div class="post-content">
    <div><%= @post.content %></div>
    <div><%= image_tag @post.picture.url if @post.picture? %></div>
  </div>

  <div class="like-btn">
    <% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>

    <% if pre_like %>
      <%= link_to image_tag("liked.svg"), post_like_path(@post, pre_like), class: "like", method: :delete, remote: true %>
    <% else %>
      <%= link_to image_tag("like.svg"), post_likes_path(@post), class: "like", method: :post, remote: true %>
    <% end %>

    <span class="counter" id="@post-counter-<%= @post.id %>">
      <%= pluralize(@post.likes.count, "like") %>
    </span>
  </div>

  <div class="edit-post">
    <% if current_user.id == @post.user_id %>
      <%= link_to "Edit", edit_post_path(@post), remote: true %>
      <%= link_to "Delete", @post, method: :delete, remote: true, data: { confirm: "Are you sure?" } %>
    <% end %>
    <div id="post-id-<%= @post.id %>"></div>
  </div>

  <div class="comments">
    <div class="comment-title">Comments (<%= @post.comments.count %>):</div>

    <div class="comment-form">
      <%= render "comments/comment_form", post: @post, comment: @post.comments.build %>
    </div>

    <div class="comment-content" id= "comments_<%= @post.id %>">
      <% if @post.comments.present? %>
        <%= render @post.comments, post: @post %>
      <% end %>
    </div>
  </div>
</div>